version: '3.9'

services:
  library-api:
    restart: always
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: library_mern_devs_nginx
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - 8000:8000
    depends_on:
      - mongodb
    environment:
      NODE_DEV: ${NODE_DEV}
      MONGO_URI: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb
    networks:
      - library-marn-api

  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes: 
      - mongodb-data:/data/db
    networks:
      - library-mern-api

  mongo_express:
    image: mongo-express
    depends_on:
      - mongodb
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    volumes:
      - mongodb-data
    networks:
      - library-mern-api
    
networks:
  library-mern-api:
    driver: bridge

volumes:
  mongodb-data:
    driver: local


    
