FROM node:16-alpine3.11

LABEL version="1.0"
LABEL description="Development image form MARM API"

WORKDIR /app

COPY ["package.json","package-lock.json","./"]

RUN npm install && npm cache clean -force

COPY . .

EXPOSE 5000

CMD ["npm", "run", "dev"]

